# Generated by Django 4.1.1 on 2023-03-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psikolog', models.CharField(max_length=20, null=True)),
                ('randevu_tarihi', models.CharField(max_length=70, null=True)),
                ('randevu_saati', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
